// Auto-generated by scripts/bump-version.mjs at deploy time.
// Don't edit manually — change scripts/bump-version.mjs if you need different format.
export const APP_VERSION = '1.1.1'
export const BUILD_DATE = '2026-04-16'
